tap "go-task/tap"
tap "hashicorp/tap"
tap "cloudquery/tap"
tap "microsoft/mssql-release", "https://github.com/Microsoft/homebrew-mssql-release"
tap "chandlerroth/tap"
cask_args appdir: "/Applications"

brew "asdf"
brew "awscli"
brew "cocoapods"
brew "dockutil"
brew "ffmpeg"
brew "git-lfs"
brew "hashicorp/tap/terraform"
brew "jq"
brew "k3d"
brew "kubernetes-cli"
brew "mas"
brew "minikube"
brew "mkcert"
brew "neovim"
brew "openssl"
brew "pipx"
brew "postgresql@15"
brew "yt-dlp"
# brew "dotnet"
# brew "freetds"
# brew "imessage-exporter"
# brew "msodbcsql17"
# brew "mssql-tools"
# brew "php@8.2"
# brew "unixodbc"

cask "1password-cli"
cask "android-studio"
cask "blender"
cask "brave-browser"
cask "copilot-money"
cask "expo-orbit"
cask "cursor"
cask "datagrip"
cask "docker"
cask "google-cloud-sdk"
cask "krisp"
cask "linear-linear"
cask "local"
cask "loom"
cask "monitorcontrol"
cask "obsidian"
cask "openlens"
cask "postman"
cask "proton-mail-bridge"
cask "protonvpn"
cask "proxyman"
cask "raycast"
cask "screen-studio"
cask "spotify"
cask "streamlabs"
cask "tailscale"
cask "tradingview"
cask "ultimaker-cura"
cask "yubico-authenticator"
cask "zoom"
# cask "signal"
# cask "telegram"
# cask "bartender"
# cask "chatgpt"
# cask "discord"
# cask "godot"
# cask "nvidia-geforce-now"

mas "Bear", id: 1091189122
mas "Harvest", id: 506189836
mas "Magnet", id: 441258766
mas "Slack", id: 803453959
mas "Things", id: 904280696
mas "Transmit", id: 1436522307
mas "Transporter", id: 1450874784
mas "Xcode", id: 497799835

# Add to chandlerroth/brew as cask
# cask https://cdn.wacom.com/u/productsupport/drivers/mac/professional/WacomTablet_6.3.46-1.dmg from https://www.wacom.com/en-us/getting-started/wacom-intuos
# cask https://github.com/rmcrackan/Libation
