tap "homebrew/cask-versions"
tap "go-task/tap"
tap "hashicorp/tap"
tap "cloudquery/tap"
tap "microsoft/mssql-release", "https://github.com/Microsoft/homebrew-mssql-release"
tap "chandlerroth/tap"
cask_args appdir: "/Applications"

brew "asdf"
brew "awscli"
brew "cloudquery"
brew "cocoapods"
brew "dotnet"
brew "ffmpeg"
brew "firebase-cli"
brew "flyctl"
brew "freetds"
brew "git-lfs"
brew "go-task"
brew "hashicorp/tap/terraform"
brew "jq"
brew "jsonnet"
brew "k3d"
brew "kubernetes-cli"
brew "mas"
brew "minikube"
brew "mkcert"
brew "msodbcsql17"
brew "mssql-tools"
brew "mysql-client"
brew "neovim"
brew "openssl"
brew "pipx"
brew "postgresql@15"
brew "unixodbc"
brew "wireshark"
brew "yarn"

cask "1password-cli"
cask "android-studio"
cask "arc"
cask "bartender"
cask "blender"
cask "brave-browser"
cask "clay"
cask "copilot-money"
cask "datagrip"
cask "discord"
cask "docker"
cask "gather"
cask "github"
cask "godot"
cask "google-cloud-sdk"
cask "krisp"
cask "linear-linear"
cask "loom"
cask "monitorcontrol"
cask "notion"
cask "obsidian"
cask "omnidisksweeper"
cask "openlens"
cask "postman"
cask "protonmail-bridge"
cask "protonvpn"
cask "proxyman"
cask "raycast"
cask "signal"
cask "spotify"
cask "streamlabs"
cask "tradingview"
cask "ultimaker-cura"
cask "visual-studio-code"
cask "zoom"

mas "Bear", id: 1091189122
mas "Harvest", id: 506189836
mas "Magnet", id: 441258766
mas "Slack", id: 803453959
mas "Things", id: 904280696
mas "Transmit", id: 1436522307
mas "Xcode", id: 497799835

# Add to chandlerroth/brew as cask
# cask https://cdn.wacom.com/u/productsupport/drivers/mac/professional/WacomTablet_6.3.46-1.dmg from https://www.wacom.com/en-us/getting-started/wacom-intuos
# cask http://releases.copilot.money/latest